version: '3.8'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./recruitdb.sql:/docker-entrypoint-initdb.d/recruitdb.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  flaskapp:
    build: .
    command: sh -c "sleep 15s ; python3 run.py"
    ports:
      - "${FLASKAPP_PORT}:${FLASKAPP_PORT}"
    depends_on:
      - mysql
    environment:
      DATABASE_URI: ${DATABASE_URI}
