apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # base64 encoded value of 'rootpassword'
  MYSQL_DATABASE: cmVjcnVpdA==  # base64 encoded value of 'recruit'

