apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-db-script
data:
  init-db.sql: |
    CREATE TABLE IF NOT EXISTS recruiter (
        id INTEGER AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(50),
        company VARCHAR(100),
        phone VARCHAR(20),
        email VARCHAR(100),
        message TEXT
    );
